baseURL = 'https://ajalab.github.io/'
languageCode = 'ja-jp'
title = 'ajalab.github.io'
theme = 'notes'

[outputs]
home = ['html', 'rss']
section = ['html']
taxonomy = ['html']
term = ['html']

[markup.goldmark.renderer]
unsafe = true
